### ISSUE TITLE
Next.js and react-hook-form - 'window is not defined'

### ISSUE THREAD

**Issue by devandnow** [tomliangg/react-hook-recaptcha#3]
Hi your example with react-hook-form is giving me the window not defined error - I've tried dynamically loading the component but to no avail likewise useEffect - any idea as to whta I should do to stop it rendering before the window has loaded?

Thanks

**Comment by tomliangg** [comment]
Looks like Next.js tried to execute the codes in your React component before DOM is available. One way to get around is force Next.js not to render any components until `ComponentDidMount` lifecycle event kicks in at `pages/index.js`. This should do it:

```jsx
import { useState, useEffect } from "react";
import MyApp from "./MyApp";

export default function Home() {
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  return (
    mounted && (
      <MyApp />
    )
  );
}

```

**Comment by tomliangg** [comment]
See: https://stackblitz.com/edit/nextjs-d6lo2e?file=pages/index.js

**Comment by devandnow** [comment]
hah so I had it bound into a useEffect already - but wasn't halting the render and the call to the disable buttons was rendering before the dom...

Thanks Tom!

**Comment by devandnow** [comment]
Closing as resolved
