### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by web-programmer-here** [tomliangg/react-hook-recaptcha#6]
Hi
are you going to support typescript ?

**Comment by tomliangg** [comment]
I can add it when I get some time next week.

**Comment by tomliangg** [comment]
hi @web-programmer-here 
I added type support and release [2.0](https://www.npmjs.com/package/react-hook-recaptcha/v/2.0.0)

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/23287044/215418483-ced9e2a8-d5f4-4f22-ab9a-3040083c3e08.png">

<img width="943" alt="image" src="https://user-images.githubusercontent.com/23287044/215418539-cfaace44-be51-4f54-a462-7b5c6ec1a782.png">

Lmk if you have any questions.
