### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by callmejm** [tomliangg/react-hook-recaptcha#7]
![image](https://user-images.githubusercontent.com/6957533/221497654-8c05ec99-ed5b-4704-bfe5-4dbef784743a.png)

facing this issue

**Comment by tomliangg** [comment]
Hi @callmejm,

Your issue might be related to https://github.com/facebook/react/issues/13991.

What bundler are you using? I bet it's create-react-app. You may find a lot of different ways to resolve the issue in the link pasted above. 

One very easy workaround is to upgrade your react and react-dom to 18.2.0 or above. Please see https://stackblitz.com/edit/react-ts-xvw4qv?file=package.json,App.tsx for examples.
