### ISSUE TITLE
2 forms in one page doesn't work

### ISSUE THREAD

**Issue by rohankhudedev** [tomliangg/react-hook-recaptcha#8]
I have 2 forms which uses re-captcha in one page. in both forms i have used different containerId.  When i use the form in different page re-captcha widget appears as expected. But when I use 2 forms in one page, then widget appears only to one form.

**Comment by tomliangg** [comment]
Can you share your codes?
While it's not conventional to place 2 forms on the same page, you can still do it; and you can call `useRecaptcha` twice with different props.

Alternatively, you can revise the design to use one form per page. I am trying to understand what you are trying to achieve with 2 forms. Can you not use a multi-step UI?

**Comment by rohankhudedev** [comment]
I have subscription form in footer which shared across website. So any page which has form like contact us page form will clash with subscription form.

**Comment by tomliangg** [comment]
you can use `useRecaptcha` hook multiple times just like `useState`

https://codesandbox.io/p/sandbox/userecaptcha-two-forms-f3nh8m
